#!/usr/bin/env node
// Ableton DJ MCP - Electronic music production MCP server for Ableton Live
// Copyright (C) 2026 Gabriel Pulga
// SPDX-License-Identifier: GPL-3.0-or-later

/**
 * Generate src/generated/build-info.ts with git branch, sha, dirty flag, and
 * build time. Imported by the live-api-adapter and mcp-server bundles so the
 * startup banner shows exactly which source state is running.
 *
 * Falls back to "local-no-git" when not in a git repo, or "release" when the
 * RELEASE_BUILD env flag is set (CI release pipelines).
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const outDir = join(repoRoot, "src", "generated");
const outFile = join(outDir, "build-info.ts");

/**
 * Run a git command and return trimmed stdout, or null on failure.
 * @param args - Git command arguments
 * @returns Command output, or null when git is unavailable / cwd not a repo
 */
function tryGit(args: string[]): string | null {
  try {
    return execFileSync("git", args, {
      cwd: repoRoot,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    return null;
  }
}

interface BuildInfo {
  branch: string;
  sha: string | null;
  dirty: boolean;
  buildTime: string;
  source: "local" | "release" | "local-no-git";
}

/**
 * Collect git-derived build identifiers and the current build timestamp.
 * @returns Build info with branch, sha, dirty flag, build time, and source
 */
function collectBuildInfo(): BuildInfo {
  const sha = tryGit(["rev-parse", "--short=8", "HEAD"]);
  const isReleaseBuild = process.env.RELEASE_BUILD === "true";

  if (sha == null) {
    // No git history available. Distinguish CI release tarballs (env flag set
    // by the release pipeline) from a hand-built local copy where we can't
    // identify the source state at all — never lie and call the latter "release".
    return {
      branch: isReleaseBuild ? "release" : "local-no-git",
      sha: null,
      dirty: false,
      buildTime: new Date().toISOString(),
      source: isReleaseBuild ? "release" : "local-no-git",
    };
  }

  const branch = tryGit(["rev-parse", "--abbrev-ref", "HEAD"]) ?? "detached";
  const status = tryGit(["status", "--porcelain"]) ?? "";
  // Treat dist/ and generated changes as ignorable for dirty detection so a
  // freshly-built tree on a clean branch still reports clean.
  const meaningfulChanges = status
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .filter((line) => {
      const path = line.slice(2).trim();

      if (path.startsWith("dist/")) return false;
      if (path.startsWith("src/generated/")) return false;
      if (path.startsWith("max-for-live-device/")) return false;

      return true;
    });

  return {
    branch,
    sha,
    dirty: meaningfulChanges.length > 0,
    buildTime: new Date().toISOString(),
    source: isReleaseBuild ? "release" : "local",
  };
}

/**
 * Render the build-info source file content from a BuildInfo object.
 * @param info - Build info to bake into the file
 * @returns TypeScript source for src/generated/build-info.ts
 */
function render(info: BuildInfo): string {
  return `// Ableton DJ MCP - Electronic music production MCP server for Ableton Live
// Copyright (C) 2026 Gabriel Pulga
// SPDX-License-Identifier: GPL-3.0-or-later

// AUTO-GENERATED by scripts/generate-build-info.ts. Do not edit.
// Regenerated by every \`npm run build\`. Gitignored.

export interface BuildInfo {
  readonly branch: string;
  readonly sha: string | null;
  readonly dirty: boolean;
  readonly buildTime: string;
  readonly source: "local" | "release" | "local-no-git";
}

export const BUILD_INFO: BuildInfo = ${JSON.stringify(info, null, 2)} as const;

/**
 * Compact build identifier for the startup banner.
 * Examples:
 *   "[main@a1b2c3d4] built 2026-05-07T12:47:18Z"
 *   "[gabriel/browser-api@a1b2c3d4*] built 2026-05-07T12:47:18Z"
 *   "[release] built 2026-05-07T08:00:00Z"
 *   "[local-no-git] built 2026-05-07T08:00:00Z"
 * @returns Compact build identifier string
 */
export function buildIdentifier(): string {
  const i = BUILD_INFO;

  if (i.sha == null) {
    return \`[\${i.source}] built \${i.buildTime}\`;
  }

  const dirtyMark = i.dirty ? "*" : "";

  return \`[\${i.branch}@\${i.sha}\${dirtyMark}] built \${i.buildTime}\`;
}
`;
}

/**
 * Generate the build-info file at src/generated/build-info.ts.
 */
function main(): void {
  const info = collectBuildInfo();

  mkdirSync(outDir, { recursive: true });
  writeFileSync(outFile, render(info), "utf8");
  console.log(
    `generate-build-info: ${info.source} ${info.branch}@${info.sha ?? "?"}${info.dirty ? "*" : ""} (${info.buildTime})`,
  );
}

main();
